#!/usr/bin/env bash

# Context, this script is for browse and search stuff from command-line
platform=$1

input_string=$2

declare -a words_array

OLD_IFS=$IFS

IFS=' '

read -ra words_array <<< "$input_string"

IFS=$OLD_IFS

google="https://www.google.com/search?client=firefox-b-d&q="
youtube="https://www.youtube.com/results?search_query="
google_images="https://www.google.com/search?q="
unsplash="https://unsplash.com/s/photos/"
spotify="https://open.spotify.com/search/"

browse () {
  if ps -A | grep -q "firefox"; then
    xdg-open $1
  else
    nohup firefox >/dev/null 2>&1 &
    sleep 2
    xdg-open $1
  fi
}

if [ "$platform" == "--google" ]; then
  for word in "${words_array[@]}"; do
    google+="$word+"
  done
  browse $google
elif [ "$platform" == "--youtube" ]; then
  for word in "${words_array[@]}"; do
    youtube+="$word+"
  done
  browse $youtube
elif [ "$platform" == "--google-img" ]; then
  for word in "${words_array[@]}"; do
    google_images+="$word+"
  done
  browse "$google_images&tbm=isch&ved=2ahUKEwjRqcy80cGAAxU5JLkGHa5IDYwQ2-cCegQIABAA&oq=Audra+miller+nice+ass&gs_lcp=CgNpbWcQDFAAWABgAGgAcAB4AIABAIgBAJIBAJgBAKoBC2d3cy13aXotaW1n&sclient=img&ei=WTfMZJGZJbnI5OUPrpG14Ag&bih=761&biw=1430&client=firefox-b-d"
elif [ "$platform" == "--unsplash" ]; then
  for word in "${words_array[@]}"; do
    unsplash+="$word-"
  done
  browse "$unsplash"
elif [ "$platform" == "--spotify" ]; then
  for word in "${words_array[@]}"; do
    spotify+="$word%20"
  done
  browse "$spotify"
else 
  echo 'only --google, --youtube, --google-img valid options.'
fi

exit 0
